[build]
  command = "gatsby build && netlify-lambda build src/lambda"
  functions = "./functions"

[context.production]
  environment = { TYPE = 'production' }

[context.staging]
  environment = { TYPE = 'staging' }
